service: serverless-auto-update-cloudfront-ips-node

provider:
  name: aws
  runtime: nodejs4.3
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

  iamRoleStatements:
    - Effect: Allow
      Action:
        - ec2:AuthorizeSecurityGroupIngress
        - ec2:RevokeSecurityGroupIngress
      Resource:
        Fn::Join:
          - ""
          -
            - "arn:aws:ec2:${self:provider.region}:"
            - ${self:custom.accountId}
            - ":security-group/*"
    - Effect: Allow
      Action:
        - ec2:DescribeSecurityGroups
      Resource:
        - "*"

custom: ${file(env/${self:provider.stage}/secrets.yml)}

functions:
  func:
    handler: env/${self:provider.stage}/function/index.handler
    # TODO: not work properly
    #events:
    #  - sns: arn:aws:sns:us-east-1:806199016981:AmazonIpSpaceChanged
